name: CD Pipeline with Docker

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create SSH key file
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/vps_key
          chmod 600 ~/.ssh/vps_key

      - name: Add known hosts
        run: ssh-keyscan -H ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts

      - name: SSH into VPS and Deploy Container with Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/vps_key ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} << 'EOF'
            cd ~/fastapi-book-project
            git pull origin main
            docker-compose down
            docker-compose up -d --build
          EOF

